language: node_js
node_js:
  - "v14.18.2"
cache:
  directories:
    - node_modules
before_install:
  - npm install -g npm@6.14.15
install:
  - npm install
  - npm run build
script:
  - npm run test:node