language: node_js
node_js:
  - "v14.18.2"
cache:
  directories:
    - dist
    - node_modules
    - tests/node_modules
    - tests/data
before_install:
  - npm install -g npm@6.14.15
install:
  - npm install
  - npm run build
  - cd tests
  - npm install
script:
  - npm run test:node